### PR TITLE
Updated reference to wiki pages

### PR DESCRIPTION
**Pull request by visto9259**
Updated the link to the wiki pages in README.md (#7 )

### CODE REVIEW

**Comment by visto9259** [comment]
@matwright @alexz707 
Humm... CI tests failed.  I only changed the README.  Was it working the last time you pull an update?

**Comment by alexz707** [comment]
Just had a quick look, it seems that the constant is undefined. They are already working on it:
https://github.com/xdebug/xdebug/pull/699

Try if it works again by adding the following to  <php> section in phpunit.xml.dist:

        
        <const name="XDEBUG_CC_UNUSED"  value=""/>

Should work until they have released the fix.
Regards Alex

**Comment by visto9259** [comment]
My change is only an update to README. No code change.  
We can address this on the next Pull Request that brings a code change.

**Review by matwright — APPROVED** [review]
Thanks

**Pull request merged**
