### PR TITLE
Fixing tests, added gitattributes

### PR DESCRIPTION
**Pull request by alexz707**
Fixing Travis Tests,
added Gitattributes to not export all config files and tests

### CODE REVIEW

**Comment by alexz707** [comment]
As already mention in the issue #3 the unit tests were not executed.
This pull requests fixes the unit tests and I also added a git attributes file so "unimportant" configs like travis won't be exported.

**Comment by alexz707** [comment]
Added a fix for the badges in the readme file, they were redirecting only to the badge-images.
now they redirect to the project

**Comment by alexz707** [comment]
Can one of you guys please review and tell me if that's ok? @visto9259  @matwright 
Test aren't working atm and I have many things to commit after that ;-)
Thanks  ;)

**Review by matwright — APPROVED** [review]
Excellent, thanks @alexz707

**Pull request merged**
